/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.90
 * Generated at: 2018-08-03 08:44:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_html extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"UTF-8\">\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\t<title>Admin</title>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900|Cormorant+Garamond:300,300i,400,400i,500,500i,600,600i,700,700i\">\n");
      out.write("\t<link href=\"//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/css/style.css\">\n");
      out.write("\t<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js\"></script>\n");
      out.write("\t<script src=\"//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/js/scripts.js\"></script>\n");
      out.write("    \n");
      out.write("</head>\n");
      out.write("<body style=\"background-image: url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/img/backgrounds/1.jpg');\">\n");
      out.write("  \n");
      out.write("  <!--------------------------------------------------------------------- \n");
      out.write("          \t\t\t        PHáº¦N HEADER \n");
      out.write("  ---------------------------------------------------------------------->\n");
      out.write("  <header>\n");
      out.write("  \t<a href=\"admin.html\" class=\"header-brand\">runsystem</a>\n");
      out.write("  \t<nav>\n");
      out.write("  \t  <ul>\n");
      out.write("  \t    <li><a href=\"#\"></a></li>\n");
      out.write("  \t  </ul>\n");
      out.write("  \t  <a href=\"#\" class=\"header-logout\">Logout</a>\n");
      out.write("  \t</nav>\n");
      out.write("  </header>\n");
      out.write("  \n");
      out.write("  \n");
      out.write("  <!--------------------------------------------------------------------- \n");
      out.write("          \t\t\t        PHáº¦N DATATABLES\n");
      out.write("  ---------------------------------------------------------------------->\n");
      out.write("  <div class=\"container\" style=\"background-color: #fff; border-radius: 10px;box-shadow: 0 0 10px #fff;\">\n");
      out.write("    <div class=\"row\">\n");
      out.write("      <div class=\"col-md-12\">\n");
      out.write("        \n");
      out.write("        <h3 style=\"color: #111;\">Datatable of Student</h3>\n");
      out.write("        <!--------------------------------------------------------------------- \n");
      out.write("                \t\t\t        PHáº¦N SEARCH\n");
      out.write("        ---------------------------------------------------------------------->\n");
      out.write("        <form id=\"form-search\" class=\"form-horizontal\" role=\"form\" method=\"post\">\n");
      out.write("\t \t  <div class=\"form-group\">\n");
      out.write("\t        <label for=\"contain\">Student Code</label>\n");
      out.write("            <input class=\"form-control\" type=\"text\" name=\"studentCode\"/>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"form-group\">\n");
      out.write("            <label for=\"contain\">Student Name</label>\n");
      out.write("            <input class=\"form-control\" type=\"text\" name=\"studentName\"/>\n");
      out.write("          </div>\n");
      out.write("          <button type=\"submit\" class=\"btn btn-primary\"><span class=\"glyphicon glyphicon-search\" aria-hidden=\"true\"></span></button>\n");
      out.write("\t    </form>  \n");
      out.write("        <div class=\"table-responsive\">        \n");
      out.write("          \n");
      out.write("          <!--------------------------------------------------------------------- \n");
      out.write("          \t\t\t\t\t\t       PHáº¦N DATATABLES \n");
      out.write("           ---------------------------------------------------------------------->\n");
      out.write("          <table id=\"mytable\" class=\"table table-bordred table-striped\">\n");
      out.write("            \n");
      out.write("            <!-- HEAD -->\n");
      out.write("            <thead style=\"background-color: #659bf6; color: #111;\">\n");
      out.write("\t\t\t  <th><input type=\"checkbox\" id=\"checkall\" /></th>\n");
      out.write("\t\t\t  <th>Code</th>\n");
      out.write("\t\t\t  <th>Name</th>\n");
      out.write("\t\t\t  <th>Date of Birth</th>\n");
      out.write("\t\t\t  <th>Avg Scores</th>\n");
      out.write("              <th>Address</th>\n");
      out.write("\t\t\t  <th>Edit</th>\n");
      out.write("\t\t\t  <th>Delete</th>\n");
      out.write("            </thead>\n");
      out.write("   \t\t\t<!--  BODY  -->\n");
      out.write("   \t\t\t<tbody id=\"table-result\" style=\"text-align: left;\">\n");
      out.write("\t\t\t\t<!-- ThÃ´ng tin danh sÃ¡ch student sáº½ ÄÆ°á»£c insert táº¡i ÄÃ¢y  -->\n");
      out.write(" \t\t\t\n");
      out.write(" \t\t\t</tbody>\n");
      out.write("          </table>\n");
      out.write("\n");
      out.write("          <!--------------------------------------------------------------------- \n");
      out.write("          \t\t\t\t\t\t       PHáº¦N PAGENATION \n");
      out.write("           ---------------------------------------------------------------------->\n");
      out.write("          \n");
      out.write("\t\t  <div class=\"clearfix\"></div>\n");
      out.write("\t\t  <div class=\"create-remove pull-left\">\n");
      out.write("\t\t  \t<button id=\"remove-list\" class=\"btn-danger\" data-title=\"Delete\" data-toggle=\"modal\" data-target=\"#delete-list\" data-placement=\"top\" rel=\"tooltip\">Remove</button>\n");
      out.write("\t\t  \t<button class=\"btn-primary\" data-title=\"Create new student\" data-toggle=\"modal\" data-target=\"#create\" data-placement=\"top\" rel=\"tooltip\">Create new</button>\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t  <ul class=\"pagination pull-right\">\n");
      out.write("\t\t    <!-- \n");
      out.write("\t\t    <li id=\"prev\" class=\"disabled\"><a href=\"#\" data-toggle=\"tooltip\" title=\"Previous\"><span class=\"glyphicon glyphicon-chevron-left\"></span></a></li>\n");
      out.write("\t\t    <li class=\"active\"><a href=\"#\">1</a></li>\n");
      out.write("\t\t    <li id=\"next\"><a href=\"#\" data-toggle=\"tooltip\" title=\"Next\"><span class=\"glyphicon glyphicon-chevron-right\"></span></a></li>\n");
      out.write("\t\t     -->\n");
      out.write("\t\t  </ul>\n");
      out.write("                \n");
      out.write("        </div> <!-- káº¿t thÃºc .table-responsive -->\n");
      out.write("      </div> <!-- káº¿t thÃºc .col-md-12 -->\n");
      out.write("\t</div> <!-- káº¿t thÃºc .row -->\n");
      out.write("  </div> <!-- káº¿t thÃºc .container -->\n");
      out.write("\n");
      out.write("\n");
      out.write("  <!--------------------------------------------------------------------- \n");
      out.write("          \t\t\t PHáº¦N POPUP MODEL UPDATE STUDENT INFO\n");
      out.write("  ---------------------------------------------------------------------->\n");
      out.write("  <div class=\"modal fade\" id=\"edit\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"edit\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog\">\n");
      out.write("      <div class=\"modal-content\">\n");
      out.write("        <div class=\"modal-header\">\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">x</button>\n");
      out.write("          <h4 class=\"modal-title custom_align\" id=\"Heading\">Edit Student</h4>\n");
      out.write("        </div>\n");
      out.write("        <form id=\"form-update\" action=\"\"  method=\"post\">\n");
      out.write("\t        <div class=\"modal-body\">\n");
      out.write("\t          <!-- Student code -->\n");
      out.write("\t          <div class=\"form-group\">\n");
      out.write("\t            <input id=\"code-update\" class=\"form-control \" type=\"text\" name=\"studentCode\">\n");
      out.write("\t          </div>\n");
      out.write("\t          \n");
      out.write("\t          <!-- Student name -->\n");
      out.write("\t          <div class=\"form-group\">\n");
      out.write("\t            <input id=\"name-update\" class=\"form-control \" type=\"text\" name=\"studentName\">\n");
      out.write("\t          </div>\n");
      out.write("\t          \n");
      out.write("\t          <!-- Student date -->\n");
      out.write("\t          <div class=\"form-group\">\n");
      out.write("\t            <input id=\"date-update\" class=\"form-control \" type=\"date\" name=\"dateOfBirth\">\n");
      out.write("\t          </div>\n");
      out.write("\t          \n");
      out.write("\t          <!-- Average Scores -->\n");
      out.write("\t          <div class=\"form-group\">\n");
      out.write("\t            <input id=\"scores-update\" class=\"form-control \" type=\"text\" name=\"avgScore\">\n");
      out.write("\t          </div>\n");
      out.write("\t          \n");
      out.write("\t          <!-- Address -->\n");
      out.write("\t          <div class=\"form-group\">\n");
      out.write("\t            <textarea id=\"address-update\" rows=\"2\" class=\"form-control\" name=\"address\"></textarea>\n");
      out.write("\t          </div>\n");
      out.write("\t        </div>\n");
      out.write("\t        <input id=\"id-update\" type=\"hidden\" name=\"studentId\">\n");
      out.write("\t        <div class=\"modal-footer \">\n");
      out.write("\t          <button type=\"submit\" class=\"btn btn-warning btn-lg\" style=\"width: 100%;\">Update</button>\n");
      out.write("\t        </div>\n");
      out.write("        </form>\n");
      out.write("      </div> <!-- káº¿t thÃºc .modal-content --> \n");
      out.write("    </div> <!-- káº¿t thÃºc .modal-dialog --> \n");
      out.write("  </div>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("  <!--------------------------------------------------------------------- \n");
      out.write("          \t\t\t PHáº¦N POPUP MODEL DELETE STUDENT \n");
      out.write("  ---------------------------------------------------------------------->\n");
      out.write("  <div class=\"modal fade\" id=\"delete\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"edit\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog\">\n");
      out.write("      <div class=\"modal-content\">\n");
      out.write("        <div class=\"modal-header\">\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">x</button>\n");
      out.write("          <h4 class=\"modal-title custom_align\" id=\"Heading\">Delete this entry</h4>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"modal-body\">\n");
      out.write("          <div class=\"alert alert-warning\"><span class=\"glyphicon glyphicon-warning-sign\"></span> Are you sure you want to delete this Student?</div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-footer \">\n");
      out.write("          <button type=\"button\" class=\"btn btn-warning\" >Yes</button>\n");
      out.write("        </div>\n");
      out.write("      </div> <!-- káº¿t thÃºc .modal-content --> \n");
      out.write("    </div> <!-- káº¿t thÃºc .modal-dialog --> \n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  \n");
      out.write("   <!--------------------------------------------------------------------- \n");
      out.write("          \t\t\t PHáº¦N POPUP MODEL DELETE LIST \n");
      out.write("  ---------------------------------------------------------------------->\n");
      out.write("  <div class=\"modal fade\" id=\"delete-list\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"edit\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog\">\n");
      out.write("      <div class=\"modal-content\">\n");
      out.write("        <div class=\"modal-header\">\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">x</button>\n");
      out.write("          <h4 class=\"modal-title custom_align\" id=\"Heading\">Delete this entry</h4>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"modal-body\">\n");
      out.write("          <div class=\"alert alert-warning\"><span class=\"glyphicon glyphicon-warning-sign\"></span> Are you sure you want to delete this Student?</div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-footer \">\n");
      out.write("          <button id=\"accept-deletes\" type=\"button\" class=\"btn btn-warning\" >Yes</button>\n");
      out.write("        </div>\n");
      out.write("      </div> <!-- káº¿t thÃºc .modal-content --> \n");
      out.write("    </div> <!-- káº¿t thÃºc .modal-dialog --> \n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write(" <!--------------------------------------------------------------------- \n");
      out.write("          \t\t\t PHáº¦N POPUP MODEL CREATE NEW STUDENT\n");
      out.write("  ---------------------------------------------------------------------->\n");
      out.write("   <div class=\"modal fade\" id=\"create\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"edit\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog\">\n");
      out.write("      <div class=\"modal-content\">\n");
      out.write("        <div class=\"modal-header\">\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">x</button>\n");
      out.write("          <h4 class=\"modal-title custom_align\" id=\"Heading\">Create New Student</h4>\n");
      out.write("        </div>\n");
      out.write("        <form action=\"\" id=\"create-form\" method=\"post\">\n");
      out.write("\t        <div class=\"modal-body\">\n");
      out.write("\t          <!-- Student's code -->\n");
      out.write("\t          \n");
      out.write("\t          <div class=\"form-group\">\n");
      out.write("\t            <input class=\"form-control \" type=\"text\" placeholder=\"Student's code\" name=\"studentCode\">\n");
      out.write("\t          </div>\n");
      out.write("\t          \n");
      out.write("\t          <!-- Student's name -->\n");
      out.write("\t          <div class=\"form-group\">\n");
      out.write("\t            <input class=\"form-control \" type=\"text\" placeholder=\"Student's name\" name=\"studentName\">\n");
      out.write("\t          </div>\n");
      out.write("\t          \n");
      out.write("\t          <!-- Student's date of birth -->\n");
      out.write("\t          <div class=\"form-group\">\n");
      out.write("\t            <input class=\"form-control \" type=\"date\" name=\"dateOfBirth\">\n");
      out.write("\t          </div>\n");
      out.write("\t          \n");
      out.write("\t          <!-- Student's Address -->\n");
      out.write("\t          <div class=\"form-group\">\n");
      out.write("\t            <textarea rows=\"2\" class=\"form-control\" placeholder=\"Student's address\" name=\"address\"></textarea>\n");
      out.write("\t          </div>\n");
      out.write("\t        </div>\n");
      out.write("\t        <div class=\"modal-footer \">\n");
      out.write("\t          <input type=\"submit\" class=\"btn btn-warning btn-lg\" style=\"width: 100%;\" value=\"Create\">\n");
      out.write("\t        </div>\n");
      out.write("        </form>\n");
      out.write("      </div> <!-- káº¿t thÃºc .modal-content --> \n");
      out.write("    </div> <!-- káº¿t thÃºc .modal-dialog --> \n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
