/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.90
 * Generated at: 2018-08-02 10:20:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_html extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"UTF-8\">\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\t<title>Admin</title>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900|Cormorant+Garamond:300,300i,400,400i,500,500i,600,600i,700,700i\">\n");
      out.write("\t\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/bootstrap/css/bootstrap.min.css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/font-awesome/css/font-awesome.min.css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/css/form-elements.css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/css/style.css\">\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/js/main.js\"></script>\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("\t\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div id=\"header\">\n");
      out.write("\t\t<a href=\"#\" class=\"header-brand\"> RUNSYSTEM </a>\n");
      out.write("\t\t<div class=\"menu\">\n");
      out.write("\t\t\t<nav>\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" id=\"create-student\">CREATE</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</nav>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<a href=\"#\" class=\"logout\"> Logout </a>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div class=\"container-admin\">\n");
      out.write("\t\t<div class=\"search\">\n");
      out.write("\t\t\t<form action=\"\" id=\"search-form\" method=\"post\">\n");
      out.write("\t\t\t\t<table>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t<input id=\"studentcode\" name=\"studentCode\" placeholder=\"Student Code\" >\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t<input id=\"studentname\" name=\"studentName\" placeholder=\"Student Name\" >\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t<td><input type=\"submit\" id=\"search-submit\" class=\"btn btn-info btn-lg search-btn\"></td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\t\n");
      out.write("\t\n");
      out.write("\t\t<div class=\"table-title\">\n");
      out.write("\t\t\t<h2>Student list</h2>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"table-result\">\n");
      out.write("\t\t\t<table>\n");
      out.write("\t\t\t\t<thead class=\"table-head\">\n");
      out.write("\t\t\t\t\t<tr style=\"height: 50px; border-radius: 10px; background-color: #649bf6;\">\n");
      out.write("\t\t\t\t\t\t<th class=\"column1\">Select</th>\n");
      out.write("\t\t\t\t\t\t<th class=\"column2\">Student Code</th>\n");
      out.write("\t\t\t\t\t\t<th class=\"column3\">Student Name</th>\n");
      out.write("\t\t\t\t\t\t<th class=\"column4\">Date of birth</th>\n");
      out.write("\t\t\t\t\t\t<th class=\"column5\">Avg Scores</th>\n");
      out.write("\t\t\t\t\t\t<th class=\"column6\">Address</th>\n");
      out.write("\t\t\t\t\t\t<th class=\"column7\"></th>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</thead>\n");
      out.write("\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"column1 column-box\"><input type=\"checkbox\" name=\"studentid\" value=\"\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"column2\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"column3\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"column4\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"column5\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"column6\"></td>\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"column7\"><a href=\"\" >Update</a></td>\n");
      out.write("\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</tbody>\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"pagination\">\n");
      out.write("\t\t  <a href=\"#\">&laquo;</a>\n");
      out.write("\t\t  <div class=\"page-list\">\n");
      out.write("\t\t\t\t<!-- chÃ¨n element page -->\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t  <a href=\"#\">&raquo;</a>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- \n");
      out.write("\t\t <a href=\"/datnt/views/admin.html?page=1\">1</a>\n");
      out.write("\t\t  <a href=\"#\" class=\"active\">2</a>\n");
      out.write("\t\t  <a href=\"#\">3</a>\n");
      out.write("\t\t  <a href=\"#\">4</a>\n");
      out.write("\t\t  <a href=\"#\">5</a>\n");
      out.write("\t\t  <a href=\"#\">6</a>\n");
      out.write("\t\t -->\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- Create popup -->\n");
      out.write("\t<div id=\"create\" class=\"create-bg\">\n");
      out.write("\t\t<div class=\"create-content\">\n");
      out.write("\t\t\t<div class=\"create-header\">\n");
      out.write("\t\t\t\t<span>CREATE STUDENT</span>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<form id=\"create-form\" action=\"\" method=\"post\" >\n");
      out.write("\t\t\t\t<table>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td class=\"column-name\">Student Code</td>\n");
      out.write("\t\t\t\t\t\t<td><input id=\"code-create\" type=\"text\" name=\"studentCode\" ></td>\n");
      out.write("\t\t\t\t\t\t<td class=\"code-error\"></td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td class=\"column-name\">Student Name</td>\n");
      out.write("\t\t\t\t\t\t<td><input id=\"name-create\" type=\"text\" name=\"studentName\"></td>\n");
      out.write("\t\t\t\t\t\t<td class=\"name-error\"></td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td class=\"column-name\">Date of birth</td>\n");
      out.write("\t\t\t\t\t\t<td><input id=\"date-create\" type=\"date\" name=\"dateOfBirth\"></td>\n");
      out.write("\t\t\t\t\t\t<td id=\"date-error\"></td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td class=\"column-name\">Address</td>\n");
      out.write("\t\t\t\t\t\t<td><input id=\"address-create\" type=\"text\" name=\"address\" ></td>\n");
      out.write("\t\t\t\t\t\t<td id=\"address-error\"></td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\t\t\t \t<input id=\"create-submit\" type=\"submit\" name=\"submit\" value=\"Create\" class=\"btn btn-info btn-lg close-btn\">\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/bootstrap/js/bootstrap.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/js/jquery.backstretch.min.js\"></script>\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/js/scripts.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
